apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  destination:
    namespace: helm-guestbook
    server: https://kubernetes.default.svc
  project: manjeet
  source:
    path: helm-guestbook/
    repoURL: 'https://github.com/manjeetyadav19/argocd-example-apps.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-hooks
  namespace: argocd  
spec:
  destination:
    namespace: helm-hooks
    server: https://kubernetes.default.svc
  project: manjeet
  source:
    path: helm-hooks
    repoURL: 'https://github.com/manjeetyadav19/argocd-example-apps.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true


---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-kustomize
  namespace: argocd    
spec:
  destination:
    namespace: kustomize-guestbook
    server: https://kubernetes.default.svc    
  project: manjeet
  source:
    path: kustomize-guestbook
    repoURL: 'https://github.com/manjeetyadav19/argocd-example-apps.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-sync-waves
  namespace: argocd   
spec:
  destination:
    namespace: sync-waves
    server: https://kubernetes.default.svc  
  project: manjeet
  source:
    path: sync-waves
    repoURL: 'https://github.com/manjeetyadav19/argocd-example-apps.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
